spring:
  application:
    name: sso

  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: ABCabc123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # redis sentinel 集群
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 10.211.55.12:26379, 10.211.55.12:26380, 10.211.55.12:26381

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8989

mybatis:
  mapper-locations: classpath:mapper/**.xml